// Generated by CoffeeScript 1.7.0
(function() {
  var Smithsonian;

  Smithsonian = require('./index');

  Smithsonian('./test').options({
    appName: 'Custom Admin Title',
    auth: false,
    authKeys: {
      username: 'superuser',
      password: 'password'
    },
    namespace: '/admin'
  }).listen(8080);

}).call(this);
